apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  mongo-db: YmV6a29kZXJfZGI=     # base64 encoded mongodb uri
  mongo-host: bW9uZ28tc2VydmljZQ== #  mongo-host: MjcwMTc=
  jwt-secret: PT09PT09PT09PT09PT09PT09PT09PUJlektvZGVyPVNwcmluZz09PT09PT09PT09PT09PT09PT09PT09PT09PQ==    # base64 encoded "secretKey"